angular.module("myapp", ["ionic",'CoderYuan'])
    .directive('myfocus', function($timeout, $parse) {
        return {
            link: function(scope, element, attrs) {
                var model = $parse(attrs.myfocus);
                scope.$watch(model, function(value) {
                    if(value === true) {
                        $timeout(function() {
                            element[0].focus();
                        });
                    }else if(value === false){
                        $timeout(function() {
                            element[0].blur();
                        });
                    }
                });
            }
        };
    })
    .config(function($stateProvider,$urlRouterProvider,$ionicConfigProvider){
        // 去掉后退按钮的文字
        $ionicConfigProvider.backButton.text("");
        $ionicConfigProvider.backButton.previousTitleText("");
        /*tabs位于页面下面*/
        $ionicConfigProvider.platform.ios.tabs.style('standard');
        $ionicConfigProvider.platform.ios.tabs.position('bottom');
        $ionicConfigProvider.platform.android.tabs.style('standard');
        $ionicConfigProvider.platform.android.tabs.position('bottom');
        /*title居中*/
        $ionicConfigProvider.platform.ios.navBar.alignTitle('center');
        $ionicConfigProvider.platform.android.navBar.alignTitle('center');
        $ionicConfigProvider.platform.ios.backButton.previousTitleText('').icon('ion-ios-arrow-thin-left');
        $ionicConfigProvider.platform.android.backButton.previousTitleText('').icon('ion-android-arrow-back');
        $ionicConfigProvider.platform.ios.views.transition('ios');
        $ionicConfigProvider.platform.android.views.transition('android');
        $stateProvider
        /*tour*/
            .state("tour",{
                url:"/tour",
                templateUrl:"templates/tour/app.html",
                controller:"tourCtrl"
            })
            .state("tour1",{
                url:"/tour1",
                templateUrl:"templates/tour1/app.html",
                controller:"tour1Ctrl"
            })
            /*选项卡*/
            .state("tabs",{
                url:"/tabs",
                abstract:true,  // 抽象地，意思是不直接显示
                templateUrl:"templates/tabs/app.html"
            })
            /*home*/
            .state("tabs.home",{
                url:"/home?id",
                cache:'false',
                views:{"tab-home":{
                    templateUrl:"templates/home/app.html",
                    controller:"homeCtrl"
                }}
            })
            /*quxiao_order*/
            .state("cancelOrder",{
                url:"/cancelOrder",
                cache:'false',
                templateUrl:"templates/quxiao_order/app.html",
                controller:"cancelOrderCtrl"
            })
            /*C商城*/
            .state("tabs.shop",{
                url:"/shop",
                views:{"tab-mall":{
                    templateUrl:"templates/shop2/app.html",
                    controller:"shop2Ctrl"
                }}
            })
            /*C商城02*/
            .state("shop2",{
                url:"/shop2?shopid",
                templateUrl:"templates/shop/app.html",
                controller:"shopCtrl"
            })
            /*daiwancheng*/
            .state("tabs.order",{
                url:"/order",
                views:{"tab-order":{
                    templateUrl:"templates/daiwancheng/app.html",
                    controller:"themeCtrl"
                }}
            })
            /*未完成订单*/
            .state("tabs.order.todone",{
                url:"/todone",
                cache:'false',
                views:{"order-tab":{
                    templateUrl:"templates/daiwancheng/todone.html",
                    controller:"todoneCtrl"
                }}
            })
            /*D待完成订单详情*/
            .state("todonedetail",{
                url:"/todonedetail?orderid",
                cache:'false',
                templateUrl:"templates/daiwancheng_detail/app.html",
                controller:"todonedetailCtrl"
            })
            /*已完成订单*/
            .state("tabs.order.done",{
                url:"/done",
                cache:'false',
                views:{"order-tab":{
                    templateUrl:"templates/wancheng/app.html",
                    controller:"doneCtrl"
                }}
            })
            /*已完成订单详情页*/
            .state("donedetail",{
                url:"/donedetail?orderid",
                cache:'false',
                templateUrl:"templates/wancheng_detail/app.html",
                controller:"donedetailCtrl"
            })
            /*login*/
            .state("login",{
                url:"/login",
                cache:'false',
                templateUrl:"templates/login/app.html",
                controller:"loginCtrl"
            })
            /*我的*/
            .state("tabs.person",{
                url:"/person?id",
                cache:'false',
                views:{"tab-person":{
                    templateUrl:"templates/my/app.html",
                    controller:"personCtrl"
                }}
            })
            /*setting*/
            .state("setting",{
                url:"/setting?id",
                cache:'false',
                templateUrl:"templates/setting/app.html",
                controller:"settingCtrl"
            })
            /*xiugai_mima*/
            .state("setting_entry",{
                url:"/setting_entry",
                cache:'false',
                templateUrl:"templates/xiugai_mima/app.html",
                controller:"setting_entryCtrl"
            })
            /*xiugai_mima1*/
            .state("setting_entry2",{
                url:"/setting_entry2?idcode&user",
                cache:'false',
                templateUrl:"templates/xiugai_mima1/app.html",
                controller:"setting_entry2Ctrl"
            })
            /*lose_mima*/
            .state("forgetCode1",{
                url:"/forgetCode1",
                cache:'false',
                templateUrl:"templates/lose_mima/app.html",
                controller:"forgetCode1Ctrl"
            })
            /*lose_mima1*/
            .state("forgetCode2",{
                url:"/forgetCode2？user",
                cache:'false',
                templateUrl:"templates/lose_mima1/app.html",
                controller:"forgetCode2Ctrl"
            })
            /*setting_pay*/
            .state("setting_pay",{
                url:"/setting_pay",
                cache:'false',
                templateUrl:"templates/setting_pay/app.html",
                controller:"setting_payCtrl"
            })
            /*setting_pay1*/
            .state("setting_pay2",{
                url:"/setting_pay2?user&idcode",
                cache:'false',
                templateUrl:"templates/setting_pay1/app.html",
                controller:"setting_pay2Ctrl"
            })
            /*my_wallet*/
            .state("wallet",{
                url:"/wallet",
                cache:'false',
                templateUrl:"templates/my_wallet/app.html",
                controller:"walletCtrl"
            })
            /*chongzhi_type*/
            .state("chongzhi_type",{
                url:"/chongzhi_type?id",
                cache:'false',
                templateUrl:"templates/chongzhi_type/app.html",
                controller:"chongzhi_typeCtrl"
            })
            /*chongzhi*/
            .state("recharge",{
                url:"/recharge",
                cache:'false',
                templateUrl:"templates/chongzhi/app.html",
                controller:"rechargeCtrl"
            })
            /*tixian*/
            .state("withdraw",{
                url:"/withdraw",
                cache:'false',
                templateUrl:"templates/tixian/app.html",
                controller:"withdrawCtrl"
            })
            /*tixian_type*/
            .state("tixian_type",{
                url:"/tixian_type",
                cache:'false',
                templateUrl:"templates/tixian_type/app.html",
                controller:"tixian_typeCtrl"
            })
            /*add_bank*/
            .state("add_bank",{
                url:"/add_bank",
                cache:'false',
                templateUrl:"templates/add_bank/app.html",
                controller:"add_bankCtrl"
            })
            /*add_bank1*/
            .state("add_bank1",{
                url:"/add_bank1",
                cache:'false',
                templateUrl:"templates/add_bank1/app.html",
                controller:"add_bank1Ctrl"
            })
            /*blank_gl*/
            .state("bank_manage",{
                url:"/bank_manage",
                cache:'false',
                templateUrl:"templates/blank_gl/app.html",
                controller:"bank_manageCtrl"
            })
            /*payfor*/
            .state("payment",{
                url:"/payment?orderid",
                cache:'false',
                templateUrl:"templates/payfor/app.html",
                controller:"paymentCtrl"
            })
            /*safe_setting*/
            .state("safe",{
                url:"/safe",
                cache:'false',
                templateUrl:"templates/safe_setting/app.html",
                controller:"safeCtrl"
            })
            /*jianyi*/
            .state("suggest",{
                url:"/suggest",
                cache:'false',
                templateUrl:"templates/jianyi/app.html",
                controller:"suggestCtrl"
            })
            /*/!*jianyi-弹窗*!/
             .state("suggest1",{
             url:"/suggest1",
             templateUrl:"templates/jianyi-弹窗/app.html",
             controller:"appCtrl"
             })*/
            /*person*/
            .state("personal",{
                url:"/personal?id",
                cache:'false',
                templateUrl:"templates/person/app.html",
                controller:"personalCtrl"
            })
            /*jifen*/
            .state("integral",{
                url:"/integral",
                cache:'false',
                templateUrl:"templates/jifen/app.html",
                controller:"integralCtrl"
            })
            /*D评论*/
            .state("comment",{
                url:"/comment?orderid",
                cache:'false',
                templateUrl:"templates/comment/app.html",
                controller:"commentCtrl"
            })
            /*comment1*/
            .state("comment1",{
                url:"/comment1?id",
                cache:'false',
                templateUrl:"templates/comment1/app.html",
                controller:"comment1Ctrl"
            })
            /*shifu_zhuce*/
            .state("register2",{
                url:"/register2",
                cache:'false',
                templateUrl:"templates/shifu_zhuce/app.html",
                controller:"register2Ctrl"
            })
            /*shifu_zhuce1*/
            .state("register2_2",{
                url:"/register2_2?idcode&user",
                cache:'false',
                templateUrl:"templates/shifu_zhuce1/app.html",
                controller:"register2_2Ctrl"
            })
            /*id*/
            .state("id",{
                url:"/id?userid",
                cache:'false',
                templateUrl:"templates/id/app.html",
                controller:"idCtrl"
            })
            /*about*/
            .state("about",{
                url:"/about",
                cache:'false',
                templateUrl:"templates/about/app.html",
                controller:"aboutCtrl"
            })
            /*map*/
            .state("map",{
                url:"/map",
                /*cache:'false',*/
                templateUrl:"templates/map/app.html",
                controller:"mapCtrl"
                /*reload:true*/
            })
            /*revise_address*/
            .state("revise_address",{
                url:"/revise_address",
                cache:'false',
                templateUrl:"templates/revise_address/app.html",
                controller:"revise_addressCtrl"
            })
            /*师傅端*/
            /*选项卡*/
            .state("tabs_sf",{
                url:"/tabs",
                abstract:true,  // 抽象地，意思是不直接显示
                templateUrl:"templates/tabs_sf/app.html"
            })
            /*home_s*/
            .state("tabs_sf.home_s",{
                url:"/home_s",
                cache:'false',
                views:{"tab-home":{
                    templateUrl:"templates/home_s/app.html",
                    controller:"home_sCtrl"
                }}
            })
            /*home_sf*/
            .state("tabs_sf.home_sf",{
                url:"/home_sf?id",
                cache:'false',
                views:{"tab-home":{
                    templateUrl:"templates/home_sf/app.html",
                    controller:"home_sfCtrl"
                }}
            })
            /*quxiao_order_sf*/
            .state("cancelOrder_sf",{
                url:"/cancelOrder_sf?id",
                cache:'false',
                templateUrl:"templates/quxiao_order_sf/app.html",
                controller:"cancelOrder_sfCtrl"
            })
            /*C商城*/
            .state("tabs_sf.shop_sf",{
                url:"/shop_sf",
                views:{"tab-mall":{
                    templateUrl:"templates/shop2_sf/app.html",
                    controller:"shop2_sfCtrl"
                }}
            })
            /*C商城02*/
            .state("shop2_sf",{
                url:"/shop2_sf?shopid",
                templateUrl:"templates/shop_sf/app.html",
                controller:"shop_sfCtrl"
            })
            /*daiwancheng_sf*/
            .state("tabs_sf.order_sf",{
                url:"/order",
                views:{"tab-order":{
                    templateUrl:"templates/daiwancheng_sf/app.html",
                    controller:"theme_sfCtrl"
                }}
            })
            /*未完成订单*/
            .state("tabs_sf.order_sf.todone_sf",{
                url:"/todone_sf",
                cache:'false',
                views:{"order-tab":{
                    templateUrl:"templates/daiwancheng_sf/todone.html",
                    controller:"todone_sfCtrl"
                }}
            })
            /*D待完成订单详情*/
            .state("todonedetail_sf",{
                url:"/todonedetail_sf?orderid",
                cache:'false',
                templateUrl:"templates/daiwancheng_detail_sf/app.html",
                controller:"todonedetail_sfCtrl"
            })
            /*已完成订单*/
            .state("tabs_sf.order_sf.done_sf",{
                url:"/done_sf",
                cache:'false',
                views:{"order-tab":{
                    templateUrl:"templates/wancheng_sf/app.html",
                    controller:"done_sfCtrl"
                }}
            })
            /*已完成订单详情页*/
            .state("donedetail_sf",{
                url:"/donedetail_sf?orderid",
                cache:'false',
                templateUrl:"templates/wancheng_detail_sf/app.html",
                controller:"donedetail_sfCtrl"
            })
            /*login_sf*/
            .state("login_sf",{
                url:"/login_sf",
                cache:'false',
                templateUrl:"templates/login_sf/app.html",
                controller:"login_sfCtrl"
            })
            /*我的*/
            .state("tabs_sf.person_sf",{
                url:"/person_sf?id",
                cache:'false',
                views:{"tab-person":{
                    templateUrl:"templates/my_sf/app.html",
                    controller:"person_sfCtrl"
                }}
            })
            /*setting*/
            .state("setting_sf",{
                url:"/setting_sf",
                cache:'false',
                templateUrl:"templates/setting_sf/app.html",
                controller:"setting_sfCtrl"
            })
            /*xiugai_mima_sf*/
            .state("setting_entry_sf",{
                url:"/setting_entry_sf",
                cache:'false',
                templateUrl:"templates/xiugai_mima_sf/app.html",
                controller:"setting_entry_sfCtrl"
            })
            /*xiugai_mima1_sf*/
            .state("setting_entry2_sf",{
                url:"/setting_entry2_sf",
                cache:'false',
                templateUrl:"templates/xiugai_mima1_sf/app.html",
                controller:"setting_entry2_sfCtrl"
            })
            /*lose_mima_sf*/
            .state("forgetCode1_sf",{
                url:"/forgetCode1_sf",
                cache:'false',
                templateUrl:"templates/lose_mima_sf/app.html",
                controller:"forgetCode1_sfCtrl"
            })
            /*lose_mima1_sf*/
            .state("forgetCode2_sf",{
                url:"/forgetCode2_sf?user&idcode",
                cache:'false',
                templateUrl:"templates/lose_mima1_sf/app.html",
                controller:"forgetCode2_sfCtrl"
            })
            /*setting_pay_sf*/
            .state("setting_pay_sf",{
                url:"/setting_pay_sf",
                cache:'false',
                templateUrl:"templates/setting_pay_sf/app.html",
                controller:"setting_pay_sfCtrl"
            })
            /*setting_pay1_sf*/
            .state("setting_pay2_sf",{
                url:"/setting_pay2_sf?user&idcode",
                cache:'false',
                templateUrl:"templates/setting_pay1_sf/app.html",
                controller:"setting_pay2_sfCtrl"
            })
            /*my_wallet_sf*/
            .state("wallet_sf",{
                url:"/wallet_sf",
                cache:'false',
                templateUrl:"templates/my_wallet_sf/app.html",
                controller:"wallet_sfCtrl"
            })
            /*chongzhi_type_sf*/
            .state("chongzhi_type_sf",{
                url:"/chongzhi_type_sf",
                cache:'false',
                templateUrl:"templates/chongzhi_type_sf/app.html",
                controller:"chongzhi_type_sfCtrl"
            })
            /*chongzhi_sf*/
            .state("recharge_sf",{
                url:"/recharge_sf",
                cache:'false',
                templateUrl:"templates/chongzhi_sf/app.html",
                controller:"recharge_sfCtrl"
            })
            /*tixian_sf*/
            .state("withdraw_sf",{
                url:"/withdraw_sf",
                cache:'false',
                templateUrl:"templates/tixian_sf/app.html",
                controller:"withdraw_sfCtrl"
            })
            /*tixian_type_sf*/
            .state("tixian_type_sf",{
                url:"/tixian_type_sf",
                cache:'false',
                templateUrl:"templates/tixian_type_sf/app.html",
                controller:"tixian_type_sfCtrl"
            })
            /*add_bank_sf*/
            .state("add_bank_sf",{
                url:"/add_bank_sf",
                cache:'false',
                templateUrl:"templates/add_bank_sf/app.html",
                controller:"add_bank_sfCtrl"
            })
            /*add_bank1_sf*/
            .state("add_bank1_sf",{
                url:"/add_bank1_sf",
                cache:'false',
                templateUrl:"templates/add_bank1_sf/app.html",
                controller:"add_bank1_sfCtrl"
            })
            /*blank_gl_sf*/
            .state("bank_manage_sf",{
                url:"/bank_manage_sf",
                cache:'false',
                templateUrl:"templates/blank_gl_sf/app.html",
                controller:"bank_manage_sfCtrl"
            })
            /*payfor_sf*/
            .state("payment_sf",{
                url:"/payment_sf?orderid",
                cache:'false',
                templateUrl:"templates/payfor_sf/app.html",
                controller:"payment_sfCtrl"
            })
            /*safe_setting_sf*/
            .state("safe_sf",{
                url:"/safe_sf",
                cache:'false',
                templateUrl:"templates/safe_setting_sf/app.html",
                controller:"safe_sfCtrl"
            })
            /*jianyi_sf*/
            .state("suggest_sf",{
                url:"/suggest_sf",
                cache:'false',
                templateUrl:"templates/jianyi_sf/app.html",
                controller:"suggest_sfCtrl"
            })
            /*/!*jianyi_sf-弹窗*!/
             .state("suggest1",{
             url:"/suggest1",
             templateUrl:"templates/jianyi_sf-弹窗/app.html",
             controller:"appCtrl"
             })*/
            /*person_sf*/
            .state("personal_sf",{
                url:"/personal_sf",
                cache:'false',
                templateUrl:"templates/person_sf/app.html",
                controller:"personal_sfCtrl"
            })
            /*jifen_sf*/
            .state("integral_sf",{
                url:"/integral_sf",
                cache:'false',
                templateUrl:"templates/jifen_sf/app.html",
                controller:"integral_sfCtrl"
            })
            /*报结工单*/
            .state("workorder_sf",{
                url:"/workorder_sf?orderid",
                cache:'false',
                templateUrl:"templates/baojiegongdan_sf/app.html",
                controller:"workorder_sfCtrl"
            })
            /*报结工单jz*/
            .state("workorder_sf_jz",{
                url:"/workorder_sf_jz?orderid",
                cache:'false',
                templateUrl:"templates/baojiegongdan_sf_jz/app.html",
                controller:"workorder_sf_jzCtrl"
            })
            /*D评论*/
            .state("comment_sf",{
                url:"/comment_sf",
                cache:'false',
                templateUrl:"templates/comment_sf/app.html",
                controller:"comment_sfCtrl"
            })
            /*comment1_sf*/
            .state("comment1_sf",{
                url:"/comment1_sf",
                cache:'false',
                templateUrl:"templates/comment1_sf/app.html",
                controller:"comment1_sfCtrl"
            })
            /*shifu_zhuce_sf*/
            .state("register2_sf",{
                url:"/register2_sf",
                cache:'false',
                templateUrl:"templates/shifu_zhuce_sf/app.html",
                controller:"register2_sfCtrl"
            })
            /*shifu_zhuce1_sf*/
            .state("register2_2_sf",{
                url:"/register2_2_sf?idcode&user",
                cache:'false',
                templateUrl:"templates/shifu_zhuce1_sf/app.html",
                controller:"register2_2_sfCtrl"
            })
            /*id*/
            .state("id_sf",{
                url:"/id_sf?workid",
                cache:'false',
                templateUrl:"templates/id_sf/app.html",
                controller:"id_sfCtrl"
            })
            /*id*/
            /*about*/
            .state("about_sf",{
                url:"/about_sf",
                cache:'false',
                templateUrl:"templates/about_sf/app.html",
                controller:"about_sfCtrl"
            })
            /*map5_sf*/
            .state("map5_sf",{
                url:"/map5_sf?id",
                cache:'false',
                templateUrl:"templates/map5_sf/app.html",
                controller:"map5_sfCtrl"
            })

            /*share*/
            .state("share",{
                url:"/share",
                cache:'false',
                templateUrl:"templates/share/app.html",
                controller:"shareCtrl"
            })
            /*price_grade*/
            .state("price_guide",{
                url:"/price_guide",
                cache:'false',
                templateUrl:"templates/price_guide/app.html",
                controller:"price_guideCtrl"
            })
            /*jz*/
            .state("jz",{
                url:"/jz",
                cache:'false',
                templateUrl:"templates/jz/app.html",
                controller:"jzCtrl"
            })
            /*jz_company*/
            .state("jz_company",{
                url:"/jz_company?type",
                cache:'false',
                templateUrl:"templates/jz_company/app.html",
                controller:"jz_companyCtrl"
            })
            /*place_order*/
            .state("place_order",{
                cache:'false',
                url:"/place_order?type&new_address&longitude&latitude&companyid&company_longitude&company_latitude",
                templateUrl:"templates/place_order/app.html",
                controller:"place_orderCtrl"
            })
            /*service_address*/
            .state("service_address",{
                cache:'false',
                url:"/service_address?type&companyid&company_longitude&company_latitude",
                templateUrl:"templates/service_address/app.html",
                controller:"service_addressCtrl"
            });
        $urlRouterProvider.otherwise("tour")
    })
    .run(['$ionicPlatform', '$ionicPopup','$rootScope','$location','$ionicHistory','$state', function ($ionicPlatform, $ionicPopup, $rootScope, $location,$ionicHistory,$state,$cordovaStatusbar) {
        document.addEventListener("deviceready", onDeviceReady, false);

        function onDeviceReady() {
            //statusbar插件-----------------
            StatusBar.hide(); //隐藏手机状态栏
        };
        //navigator.splashscreen.show();//显示启动页面
        //主页面显示退出提示框
        $ionicPlatform.registerBackButtonAction(function (e) {

            e.preventDefault();

            function showConfirm() {
                var confirmPopup = $ionicPopup.confirm({
                    title: '<strong>退出应用?</strong>',
                    template: '你确定要退出应用吗?',
                    okText: '退出',
                    cancelText: '取消'
                });
                confirmPopup.then(function (res) {
                    if (res) {
                        ionic.Platform.exitApp();
                    } else {
                        // Don't close
                    }
                });
            }
            // Is there a page to go back to?
            if ($location.path() == '/tabs/home' || $location.path() == '/tabs/shop'  || $location.path() == '/tabs/order/done' || $location.path() == '/tabs/order/todone'  || $location.path() == '/tabs/person' || $location.path() == '/tabs/home_s' || $location.path() == '/tabs/shop_sf'  || $location.path() == '/tabs/order/done_sf' || $location.path() == '/tabs/order/todone_sf'  || $location.path() == '/tabs/person_sf') {
                showConfirm();
            } else if($location.path() == '/comment1'){
                $state.go("tabs.person");
            }else if ($ionicHistory.backView()) {
                // Go back in history
                $ionicHistory.goBack();
            } else {
                // This is the last page: Show confirmation popup
                showConfirm();
            }
            return false;
        }, 101);
          //状态栏的设置


    }]);